//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Черновик
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ЧерновикEntities : DbContext
    {
        public ЧерновикEntities()
            : base("name=ЧерновикEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Единицы_измерения> Единицы_измерения { get; set; }
        public virtual DbSet<Материал> Материал { get; set; }
        public virtual DbSet<Материалы_поставщиков> Материалы_поставщиков { get; set; }
        public virtual DbSet<Поставщики> Поставщики { get; set; }
        public virtual DbSet<Тип_материала> Тип_материала { get; set; }
        public virtual DbSet<Тип_поставщиков> Тип_поставщиков { get; set; }
    }
}
