//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Черновик
{
    using System;
    using System.Collections.Generic;
    
    public partial class Материал
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Материал()
        {
            this.Материалы_поставщиков = new HashSet<Материалы_поставщиков>();
        }
    
        public int ID { get; set; }
        public string Наименование { get; set; }
        public int Ед_измерения { get; set; }
        public string Изображение { get; set; }
        public decimal Цена { get; set; }
        public string Кол_во_в_упаковке { get; set; }
        public string Минимальное_кол_во { get; set; }
        public int Тип { get; set; }
    
        public virtual Единицы_измерения Единицы_измерения { get; set; }
        public virtual Тип_материала Тип_материала { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Материалы_поставщиков> Материалы_поставщиков { get; set; }
    }
}
